server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend API Gateway (Solves Mixed Content Error)
    location /users/ {
        proxy_pass http://136.68.73.109:8080/users/;
    }
    
    location /catalog/ {
        proxy_pass http://136.68.73.109:8080/catalog/;
    }
    
    location /delivery/ {
        proxy_pass http://136.68.73.109:8080/delivery/;
    }
}