server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /users/ {
        proxy_pass http://136.68.73.109/users/;
    }
    
    location /catalog/ {
        proxy_pass http://136.68.73.109/catalog/;
    }
    
    location /delivery/ {
        proxy_pass http://136.68.73.109/delivery/;
    }
}